### ISSUE TITLE
VirusTotal shows trojan warning

### ISSUE THREAD

**Issue by cody151** [dragonfruitnetwork/onionfruit#43] opened 2024-01-12 08:44 UTC
**Describe the bug**
Please be careful as various virustotal scans detected consistent malware and system scanners auto-removed the file, beware downloading this as this is for some reason being posted on GitHub without even showing the source code which is already a red flag as nobody know what the app is really doing on your system, GitHub is supposed to show open-source code.

**Comment by aspriddell** [comment] 2024-01-12 09:42
I'll respond with some reasons why you'd get these kind of warnings:

1. OnionFruit changes proxy settings, so could be classified as malware because it changes system settings
2. It embeds and distributes other programs, so could be seen as a loader for malware
3. Because proprietary libraries are used, there is some obfuscation taking place, so could be seen as malware
4. It uses squirrel to install to the user's appdata folder, so could be blocked by anti-ransomware or anti-virus as a program that extracts another executable (see point 2)

Strangely enough, I tried [running it myself](https://www.virustotal.com/gui/file/539a4139cc11fc6583c474db75814aca7d3c82244e20e9e3f812d3583e0281b7) to see what happens and only 4 antivirus engines I've never heard of have complained.

As it states in the readme, the source code isn't distributed as 90% of the work is in the user interface, which uses telerik and postsharp which are both non-free tools. Telerik prevents distributing design-time libraries to unlicensed users and postsharp has its own system to check if users are allowed to use their tools. There's no way for me to verify if somebody has these tools and as the connection logic itself isn't that complicated I decided to not release the source code.

If you don't wish to use the program, that is totally your choice to wait for the open-source edition to be released in the near future. In the meantime, if you are going to broadcast "this is malware" to everyone, at least back it up with a link to the virus scan and ensure it's not an issue with [another tool/system](https://github.com/clowd/Clowd.Squirrel/issues/28) that's already known. If there is some evidence that is more detailed, please do share (either directly or via email) and it can be addressed as needed.

**Comment by NiKola-UE** [comment] 2024-05-31 22:36
I can confirm that OnionFruit does not contain any malware, but I also had a strange problem with antiviruses, which I will try to describe briefly. Namely, neither before nor after installation, and even after launching OnionFruit, none antivirus or Windows Defender would register anything suspicious or harmful. So the program works normally and everything is fine until I click "Toggle Tor". Well, then a problem arises in the form of an error message that roughly says that some anti-malware application disables and prevents something, which can be seen from the last "Log.txt" file(s) in which it is clearly indicated that the connection on the Tor was unsuccessful because an error occurred. At first I thought it was some problem with OnionFruit, but it turned out that the antiviruses were blocking something, regardless of the fact that, I repeat, they did not report or warn about anything harmful or dangerous. What would be the best thing to do so that such conflicts do not occur again?

**Comment by aspriddell** [comment] 2024-10-01 21:25
Closing due to inactivity - question was answered

**Closed by aspriddell** 2024-10-01 21:25 UTC
Labels: is:invalid
