### ISSUE TITLE
Your Project Violates License Restrictions

### ISSUE THREAD

**Issue by Librechain** [dragonfruitnetwork/onionfruit#33] opened 2022-12-20 08:03 UTC
You all noted that this project is entirely closed source. Something was stated about the UI, but that's wholly irrelevant since the entirety of the project is closed source.

Your project integrates the use of the Tor Network and likely interacts with the network using required libraries and code that was originally published by the Tor Network. 

Here's a copy of the license for the Tor source code: https://gitweb.torproject.org/tor.git/tree/LICENSE?id=272265efbd89c4c2589316a20cf27064def21911

Its licensed under "3-Clause BSD", which you can read in full here: https://opensource.org/licenses/BSD-3-Clause

Since your project appears to integrate code from Tor in some facet, this license should've been included here along with whatever source code applies that falls under this license. If you visit the link I gave for the Tor license, you'll notice that as you scroll down, there are additional licenses for other software, packages and programs that were compiled and integrated into the Tor source code. 

That was done because those that published the Tor source respect the license requirements of the technology they used in order to build their project. 

### The World is Bigger Than You 

I understand that you all are worried about your project being forked / idea being "stolen". However, it would help to have enough self-awareness to acknowledge that your project would have been **impossible to create** if Tor was also closed source. Fortunately for us all, it isn't. 

Having a closed source project is no problem. I'm typing this issue from a MacBook and Apple certainly has no qualms about making it clear their code is proprietary and the **source is closed**. However, they **do publish the source code for the open source programs, code, etc., they use in the creation of their products** (i.e., iPhone, MacBook, etc.). 

You can view **all the source code from open source projects that Apple uses in their products here**: https://opensource.apple.com/releases/

<img width="776" alt="image" src="https://user-images.githubusercontent.com/59129716/208598865-bf0bb507-44f0-40d5-a775-af2bed65ca2c.png">

<img width="789" alt="image" src="https://user-images.githubusercontent.com/59129716/208598912-80bc684f-bca4-4170-b4da-2ea1fd93b2c2.png">

### Why This Issue is Being Created 

Because you all took the time to create a repo on GitHub for your project explaining why you closed source **all of the code you used in its creation** and were even audacious enough to publish **your license up here** with what one could assume were expectations that said license would be observed and respected by others. 

Yet, ironically, you failed to do the same despite creating a project that essentially is built entirely on the basis of an open source project. Again, the issue is not being closed source. Its **using open source** with a complete lack of regard and respect to the associated licenses that accompany those projects while simultaneously creating a GitHub repo that's essentially dedicated to establishing **your license rights**. 

This issue is bigger than open source or licensing. Its a matter of reciprocation and fairness. That's how we all can coexist cohesively. 

Thank you in advance for taking the time to review this issue. Whether or not you all decide to take action is up to you. There are no impending consequences for your failure to do so. At least not from anyone other than yourselves. 

Few parting thoughts: 

1. While confidence is awesome (and even necessary) for developers and stakeholders in new projects, its **highly presumptuous** to suggest that folks will fork & copy your project en masse. You all have obtained no critical acclaim yet or generalized success to where this should be considered a valid concern. 
2. Developers have always had this fear that their projects being open source will lead to clones. This fear is not baseless but its also not what developers **actually fear** - and that's the idea that their original idea will be diluted by the proliferation of cheap imitations. Or, worse yet, that a true competitor with much greater resource may stumble upon their idea, fork it and bring it to market quicker than they can, which would allow that competitor to reap all the spoils of success that your team originally envisioned would go to them. This doesn't happen. Almost ever. Take a look at that list of open source projects Apple provided source code references for. Its **pretty extensive**. Why? Because there's really no reason to fork something if the original iteration is well-designed and maintained. 
3. Developers also have the idea that making their projects open source will simultaneously destroy all monetization strategies / business models. The fact is this couldn't be further from the truth. There are trade-offs that come with the decision, but in my opinion those trade offs suggest that it may be **more profitable** to open source one's project. The major benefit you get here is that you open your project up to contributions from the community, which essentially can amount to receiving expert assistance for free. Also, if you price your product appropriately, the **convenience** of paying $x/month will exceed the benefit someone may receive from averting this cost & deciding to download, compile, build & install your project. Take MullvadVPN for example. All of their code is open source yet they still are profitable as a business. How? Because nobody **really** wants to build their own VPN and its even more tedious to fork and modify the source code to the extent necessary for one to deem their version as an improvement. Keep in mind that those w the skills & expertise to do something like this are likely already deploying those skills **elsewhere**. 

That's all I got to say! Good luck with everything guys. Just some food for thought.

**Comment by aspriddell** [comment] 2022-12-20 08:19
Thanks for the issue. I'll explain our stance here and you're welcome to add any other questions you need answering.

The app is, as you correctly stated, closed-source because the components we use to build the interface are from Telerik, and we cannot supply any developers with designer libraries otherwise we'd be violating the agreement we have with them. We also use PostSharp, and while you can get their libraries from NuGet, they will force you to purchase a license so again, no point.

To run through the BSD-3 clause license:

### Redistributions of source code must retain the above copyright
notice, this list of conditions and the following disclaimer.
Compliant - the app doesn't redistribute source code

### Redistributions in binary form must reproduce the above
copyright notice, this list of conditions and the following disclaimer
in the documentation and/or other materials provided with the
distribution.
Compliant - In the application install directory, there is a file under Licenses called Tor.txt that reproduces the license and copyright notice.

### Neither the names of the copyright owners nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.

We don't advertise the app on any platform (apart from our site), but it has been picked up by software distribution sites that make the direct comparison. We don't use the name of any contributor or any copyright holders in any of the code or website material.

The licenses for all components are reproduced in the Licenses file, that you can find at `%localappdata%\OnionFruitConnect\app-2022.1123.0\Licenses`

### Remarks
The purpose of the GitHub repo is to allow people to report issues and suggest features so that they can be seen by everyone, not just over email between two people. We have also considered creating another version of the app that is open source, but are not quite at that point yet.

**Comment by aspriddell** [comment] 2022-12-22 10:24
Closing as resolved

**Closed by aspriddell** 2022-12-22 10:24 UTC
