### ISSUE TITLE
Tor process killed when using bridges

### ISSUE THREAD

**Issue by QuMix64** [dragonfruitnetwork/onionfruit#50] opened 2024-11-07 14:06 UTC
![image](https://github.com/user-attachments/assets/d9bd10c5-02a7-4760-9bb1-192177fe32d2)
Hello, OnionFruit can't connect to Tor through Bridges, it says "Tor Process killed" (Killswitch enabled). I can't use direct connection because Tor is blocked in my country. Release version on dragonfruit.network doesn't have this issue, but there's no WebTunnel bridge I need. I'd be very grateful if you respond to it

**Comment by QuMix64** [comment] 2024-11-07 14:36
Thank you for the response! Of course, I use only proven bridges that work perfectly in the Tor browser and on the phone. As I said earlier, in the release version of OnionFruit, my obfs4 bridge works
![image](https://github.com/user-attachments/assets/5ed90a55-604f-4b95-bcc3-549bc5e1d8e2)
![image](https://github.com/user-attachments/assets/b4dcc35e-6246-4784-b5ae-9d134302dbc4)
But I can't use this version because it doesn't support webtunnel

I can put the same bridge in a new version, but it doesn't work anymore
![image](https://github.com/user-attachments/assets/325f2d43-1567-4519-88c3-8ece131893b0)
![image](https://github.com/user-attachments/assets/5bbfba0e-9e1d-476a-92d4-7419fc67bb8b)

**Comment by QuMix64** [comment] 2024-11-07 15:36
[runtime.log](https://github.com/user-attachments/files/17663974/runtime.log)

**Comment by aspriddell** [comment] 2024-11-07 15:57
Thanks for that, the issue isn't on your end, it's caused when .NET builds the app and it flattens a series of folders that causes some of the files to be moved and tor crashes as a result.

I'll take a look at getting that sorted and will update here when it's resolved

**Comment by QuMix64** [comment] 2024-11-07 16:09
Thank you for your answers, I will be waiting for a new version!

**Comment by aspriddell** [comment] 2024-11-07 19:20
The flattened directories were to blame; I have changed how the config file is written so it will now correctly work out the location of the plugins.

Please launch the program, allow it to update and restart and it should work now (updates may take around 30s to complete after closing the app).

**Closed** 2024-11-07 19:25 UTC
Labels: area:bridges

**Comment by aspriddell** [comment] 2024-11-08 09:22
The bridge you've quoted is not working most likely because it's not active anymore. If you are going to report issues with bridges please make sure you are using ones from the BridgeDB and not some archive of potentially outdated ones.

Additionally, this issue is for bridges that use pluggable transports (everything except for plain ones). I have updated the title to make this clearer but if you have any further problems please create a new issue.

**Comment by aspriddell** [comment] 2024-11-09 13:17
You just have to try them, if the connection doesn't work then get some more and keep trying until they work. Pinging the server and getting a response will tell you the server is reachable, but doesn't always mean it's acting as a bridge (i.e. tor is installed and running on it)
